Madhura Vilas Suroshe

24102C2002

R Programming Week 9

#Lecture 36 — cat() and String Formatting

Cell 1 — print() vs cat()

In [14]:
# Using print()
print("The zero occurs at")
print(2*pi)
print("radians")

# Using cat()
cat("The zero occurs at", 2*pi, "radians.", "\n")

[1] "The zero occurs at"
[1] 6.283185
[1] "radians"
The zero occurs at 6.283185 radians.

Cell 2 — Date with cat()

In [15]:
d <- date()

cat("Today's date is:", d, "\n")

Today's date is: Mon Sep 21 08:47:44 2026

Cell 3 — sep in cat()

In [16]:
x <- 1:10

cat(x, sep = " ++ ")
cat("\n")

cat(x, sep = " / ")
cat("\n")

1 ++ 2 ++ 3 ++ 4 ++ 5 ++ 6 ++ 7 ++ 8 ++ 9 ++ 10
1 / 2 / 3 / 4 / 5 / 6 / 7 / 8 / 9 / 10

Cell 4 — Square of a number

In [17]:
x <- 7

cat("The square of", x, "is", x^2, "!\n")

The square of 7 is 49 !

Cell 5 — Square root and format()

In [18]:
x <- 7

cat(
  "The square root of",
  x,
  "is approximately",
  format(sqrt(x), digits = 3),
  "\n"
)

The square root of 7 is approximately 2.65

Cell 6 — Printing a vector

In [19]:
evenno <- c(2, 4, 6, 8, 10)

cat("The first few even numbers are:", evenno, "...\n")

The first few even numbers are: 2 4 6 8 10 ...

Cell 7 — fill and labels

In [20]:
x <- 1:10

cat(
  x,
  fill = 2,
  labels = paste("(", letters[1:10], "):")
)

( a ): 1
( b ): 2
( c ): 3
( d ): 4
( e ): 5
( f ): 6
( g ): 7
( h ): 8
( i ): 9
( j ): 10

#Lecture 37 — paste() Function

Cell 8 — Basic paste()

In [21]:
paste("Everybody", "loves", "R Programming.")

[1] "Everybody loves R Programming."

Cell 9 — sep

In [22]:
paste("Everybody", "loves", "R Programming.", sep = "*")

paste("Everybody", "loves", "R Programming.", sep = "===")

[1] "Everybody*loves*R Programming."

[1] "Everybody===loves===R Programming."

Cell 10 — paste() and as.character()

In [23]:
paste(1:12)

as.character(1:12)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11" "12"

Cell 11 — Vector with paste()

In [24]:
names <- c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

names

paste(names, "is", "a good", "person.")

[1] "Prof. Singh" "Mr. Venkat"  "Dr. Jha"

[1] "Prof. Singh is a good person." "Mr. Venkat is a good person."
[3] "Dr. Jha is a good person."

Cell 12 — collapse

In [25]:
names <- c(
  "Prof. Singh",
  "Mr. Venkat",
  "Dr. Jha"
)

paste(
  names,
  "is",
  "a good",
  "person.",
  collapse = ", and "
)

[1] "Prof. Singh is a good person., and Mr. Venkat is a good person., and Dr. Jha is a good person."

#Operations with Strings

Cell 13 — paste() with numbers

In [26]:
paste(
  1,
  " is first",
  2,
  " is second",
  3,
  " is third",
  sep = "#"
)

[1] "1# is first#2# is second#3# is third"

Cell 14 — Spaces matter

In [27]:
paste(
  1,
  " is first ",
  2,
  " is second ",
  3,
  " is third ",
  sep = "#"
)

[1] "1# is first #2# is second #3# is third "

Cell 15 — Creating "Ex_1" to "Ex_5"

In [28]:
x <- paste("Ex", 1:5, sep = "_")

x

x[1]
x[2]
x[3]
x[4]
x[5]

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

[1] "Ex_1"

[1] "Ex_2"

[1] "Ex_3"

[1] "Ex_4"

[1] "Ex_5"

#collapse vs normal paste()

In [29]:
x <- paste("Ex", 1:5, sep = "_")

x

[1] "Ex_1" "Ex_2" "Ex_3" "Ex_4" "Ex_5"

In [30]:
x <- paste("Ex", 1:5, sep = "_", collapse = "")

x

[1] "Ex_1Ex_2Ex_3Ex_4Ex_5"

#paste0()

Cell 17 — paste0() vs paste()

In [31]:
paste0(1:10)

paste(1:10)

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

 [1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10"

Cell 18 — Ordinal numbers

In [32]:
paste0(
  1:10,
  c("st", "nd", "rd", rep("th", 7))
)

 [1] "1st"  "2nd"  "3rd"  "4th"  "5th"  "6th"  "7th"  "8th"  "9th"  "10th"

#Lecture 38 — strsplit()

Cell 19 — Split using !

In [33]:
x <- "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

x

strsplit(x, split = "!")

[1] "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

[[1]]
[1] "The&"               "syntax&"            "of&"
[4] "paste&"             "is"                 "&available"
[7] "&inthe online-help"

Cell 20 — Split using "&!"

In [34]:
x <- "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

strsplit(x, split = "&!")

[[1]]
[1] "The"                              "syntax"
[3] "of"                               "paste"
[5] "is!&available!&inthe online-help"

Cell 21 — Access elements of strsplit()

In [35]:
x <- "The&!syntax&!of&!paste&!is!&available!&inthe online-help"

y <- strsplit(x, split = "!&")

y

y[[1]][1]
y[[1]][2]
y[[1]][3]

[[1]]
[1] "The&!syntax&!of&!paste&!is" "available"
[3] "inthe online-help"

[1] "The&!syntax&!of&!paste&!is"

[1] "available"

[1] "inthe online-help"

#Date splitting and Matrix

Cell 22 — Create dates

In [36]:
dates <- c(
  "2020-07-24",
  "2021-08-25",
  "2022-09-26",
  "2023-10-27"
)

dates

[1] "2020-07-24" "2021-08-25" "2022-09-26" "2023-10-27"

Cell 23 — Split dates

In [37]:
datesplt <- strsplit(dates, "-")

datesplt

[[1]]
[1] "2020" "07"   "24"

[[2]]
[1] "2021" "08"   "25"

[[3]]
[1] "2022" "09"   "26"

[[4]]
[1] "2023" "10"   "27"

Cell 24 — Convert to character matrix

In [38]:
datemat <- matrix(
  unlist(datesplt),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datemat

     [,1] [,2] [,3]
[1,] 2020 07   24
[2,] 2021 08   25
[3,] 2022 09   26
[4,] 2023 10   27

Cell 25 — Convert to numeric matrix

In [39]:
datematrix <- matrix(
  as.numeric(unlist(datesplt)),
  nrow = 4,
  ncol = 3,
  byrow = TRUE
)

datematrix

     [,1] [,2] [,3]
[1,] 2020  7   24
[2,] 2021  8   25
[3,] 2022  9   26
[4,] 2023 10   27

Cell 26 — Split every character

In [40]:
strsplit("Shalabh", split = "")

[[1]]
[1] "S" "h" "a" "l" "a" "b" "h"

#Lecture 39 — Counting Characters

Cell 27 — nchar()

nchar() returns the number of characters in each element of a character vector.

In [41]:
x <- "R course 24.07.2022"
y <- "Number of participants: 25"

nchar(x)
nchar(y)

[1] 19

[1] 26

Cell 28 — nzchar()

In [42]:
x <- "R course 24.07.2022"
y <- "Number of participants: 25"

nzchar(x)
nzchar(y)

[1] TRUE

[1] TRUE

Cell 29 — nzchar() with empty string

In [43]:
x <- c("Apple", "Banana", "Cake")

x
nzchar(x)

y <- c("Apple", "", "Cake")

y
nzchar(y)

[1] "Apple"  "Banana" "Cake"

[1] TRUE TRUE TRUE

[1] "Apple" ""      "Cake"

[1]  TRUE FALSE  TRUE

nchar() with vectors and numbers

In [44]:
x <- c("Apple", "Banana", "Cake")

nchar(x)

[1] 5 6 4

In [45]:
y <- c(2, 4, 6)

nchar(y)

[1] 1 1 1

In [46]:
z <- c(11, 222, 3333)

nchar(z)

[1] 2 3 4

#Lowercase and Uppercase

Cell 31 — toupper()

In [47]:
x <- "R course will start from 24.07.2022"

x

toupper(x)

[1] "R course will start from 24.07.2022"

[1] "R COURSE WILL START FROM 24.07.2022"

Cell 32 — tolower()

In [48]:
z <- "INDIAN INSTITUTE OF TECHNOLOGY"

z

tolower(z)

[1] "INDIAN INSTITUTE OF TECHNOLOGY"

[1] "indian institute of technology"