1. Renaming Row and Column Names

In [2]:
x <- matrix(nrow=4, ncol=3, data=1:12)
x

rownames(x) <- c("r1", "r2", "r3", "r4")
x

colnames(x) <- c("c1", "c2", "c3")
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   [,1] [,2] [,3]
r1 1    5     9
r2 2    6    10
r3 3    7    11
r4 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

2. Assigning a Number to All Matrix Elements

In [3]:
x <- matrix(nrow=4, ncol=2, data=2)
x

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

3. Identity Matrix

In [4]:
d <- diag(1, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

4. Diagonal Matrix with 5

In [5]:
d <- diag(5, nrow=3, ncol=3)
d

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

5. Transpose of Matrix

In [6]:
x <- matrix(nrow=4, ncol=2, data=1:8, byrow=TRUE)
x

xt <- t(x)
xt

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

6. Row and Column Sums

In [7]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8)
)

x

rowSums(x)
colSums(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

7. Row and Column Means

In [8]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=c(1,2,3,4,5,6,7,8)
)

x

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1] 3 4 5 6

[1] 2.5 6.5

8. Access Rows, Columns and Submatrices

In [9]:
x <- matrix(
  nrow=5,
  ncol=3,
  byrow=TRUE,
  data=1:15
)

x

# Third row
x[3,]

# Second column
x[,2]

# Rows 4 and 5, Columns 2 and 3
x[4:5, 2:3]

# Rows 1 and 4, Columns 1 and 3
x[c(1,4), c(1,3)]

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

[1] 7 8 9

[1]  2  5  8 11 14

     [,1] [,2]
[1,] 11   12
[2,] 14   15

     [,1] [,2]
[1,]  1    3
[2,] 10   12

9. Matrix + Constant

In [10]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

x + 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

10. Matrix - Constant

In [11]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

x - 5

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

11. Matrix × Constant

In [12]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

5 * x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

12. Matrix / Constant

In [13]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

x / 2

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 0.5  1
[2,] 1.5  2
[3,] 2.5  3
[4,] 3.5  4

13. Addition and Subtraction of Matrices

In [14]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

y <- matrix(
  nrow=4,
  ncol=2,
  data=11:18,
  byrow=TRUE
)

x
y

x + y
x - y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16
[4,] 17   18

     [,1] [,2]
[1,] 12   14
[2,] 16   18
[3,] 20   22
[4,] 24   26

     [,1] [,2]
[1,] -10  -10
[2,] -10  -10
[3,] -10  -10
[4,] -10  -10

14. Matrix Expressions

In [15]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

4 * x

x + 4 * x

4 * x - x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

     [,1] [,2]
[1,]  3    6
[2,]  9   12
[3,] 15   18
[4,] 21   24

15. Matrix Multiplication %*%

In [16]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

y <- matrix(
  nrow=2,
  ncol=4,
  data=11:18,
  byrow=TRUE
)

x
y

x %*% y

y %*% x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

     [,1] [,2]
[1,] 210  260
[2,] 274  340

16. X'X and XX'

In [17]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

t(x)

t(x) %*% x

x %*% t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2] [,3] [,4]
[1,]  5   11   17    23
[2,] 11   25   39    53
[3,] 17   39   61    83
[4,] 23   53   83   113

17. Cross Product

In [18]:
x <- matrix(
  nrow=4,
  ncol=2,
  data=1:8,
  byrow=TRUE
)

x

t(x) %*% x

crossprod(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1] [,2]
[1,]  84  100
[2,] 100  120

18. Row-wise Concatenation — rbind()

In [19]:
x <- matrix(
  nrow=3,
  ncol=2,
  data=1:6,
  byrow=TRUE
)

y <- matrix(
  nrow=3,
  ncol=2,
  data=11:16,
  byrow=TRUE
)

x
y

rbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

19. Column-wise Concatenation — cbind()

In [20]:
x <- matrix(
  nrow=3,
  ncol=2,
  data=1:6,
  byrow=TRUE
)

y <- matrix(
  nrow=3,
  ncol=2,
  data=11:16,
  byrow=TRUE
)

x
y

cbind(x, y)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

20. Matrix Inverse — solve()

In [21]:
y <- matrix(
  nrow=2,
  ncol=2,
  byrow=TRUE,
  data=c(84,100,100,120)
)

y

solve(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

21. Eigenvalues and Eigenvectors

In [22]:
y <- matrix(
  nrow=2,
  ncol=2,
  byrow=TRUE,
  data=c(84,100,100,120)
)

y

eigen(y)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

Logical Operators

22. | and ||

In [23]:
x <- 8

(x < 10) || (x < 2)

x <- 18

(x < 10) || (x < 2)

[1] TRUE

[1] FALSE

23. | vs || with Vector

In [27]:
# | works element-wise on vectors
x <- c(8,18)

(x < 10) | (x < 2)

[1]  TRUE FALSE

24. & and &&

In [29]:
# && works with a single value

x <- 5
(x < 10) && (x > 2)

x <- 15
(x < 10) && (x > 2)


# & works element-wise with vectors

x <- c(8,18)

(x < 10) & (x > 2)

[1] TRUE

[1] FALSE

[1]  TRUE FALSE

25. Filtering Values Using Logical Conditions

In [30]:
x <- 1:6

(x > 2) & (x < 5)

x[(x > 2) & (x < 5)]

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] 3 4

26. OR Condition

In [31]:
x <- 1:6

(x > 2) | (x < 5)

x[(x > 2) | (x < 5)]

[1] TRUE TRUE TRUE TRUE TRUE TRUE

[1] 1 2 3 4 5 6

27. && Checks First Element

In [33]:
# && works with single logical values

x <- 1:6

# Element-wise comparison
(x > 2) & (x < 5)

# Demonstrating && using only the first element
(x[1] > 2) && (x[1] < 5)

[1] FALSE FALSE  TRUE  TRUE FALSE FALSE

[1] FALSE

28. Standard Logical Operations

In [34]:
x <- TRUE
y <- FALSE

x & y

x | y

!x

[1] FALSE

[1] TRUE

[1] FALSE

29. is.logical()

In [35]:
x <- 5

Logical1 <- (x > 2)
Logical1
is.logical(Logical1)

Logical2 <- (x < 10)
Logical2
is.logical(Logical2)

Logical3 <- (x != 5)
Logical3
is.logical(Logical3)

[1] TRUE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

30. More Logical Expressions

In [36]:
x <- 5

Logical4 <- (2*x > 11)
Logical4
is.logical(Logical4)

Logical5 <- (3*x < 20)
Logical5
is.logical(Logical5)

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

Relational Operators

31. Basic Relational Operators

In [37]:
8 > 7

7 < 5

7 > 7

7 >= 7

8 < 8

8 <= 8

8 != 9

9 != 9

7 == 7

7 == 8

[1] TRUE

[1] FALSE

[1] FALSE

[1] TRUE

[1] FALSE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

[1] FALSE

32. NOT Operator

In [38]:
x <- TRUE

!x

[1] FALSE

33. Comparing Two Vectors

In [39]:
x <- c(1, 2, 3)
y <- c(4, 5, 6)

x > y

x < y

x != y

x == y

[1] FALSE FALSE FALSE

[1] TRUE TRUE TRUE

[1] TRUE TRUE TRUE

[1] FALSE FALSE FALSE

34. isTRUE()

In [40]:
isTRUE(8 < 6)

isTRUE(8 > 6)

[1] FALSE

[1] TRUE

35. isFALSE()

In [41]:
isFALSE(5 < 8)

isFALSE(5 > 8)

[1] FALSE

[1] TRUE

# Relational

(>, >=, <, <=, ==, !=)

# Logical
(!, &, &&, |, ||)

# Functions
xor()

isTRUE()

isFALSE()

is.logical()