**Madhura Vilas Suroshe**

**24102C2002**

**R Programming Week 2**


# Foundations of R - Lecture Notes Week 03
Basics of Calculations and Matrices

In [ ]:
############################################################
# 1. Vector Arithmetic
############################################################

# Addition
c(2,3,5,7) + c(-2,-3,-5,8)

# Subtraction
c(2,3,5,7) - c(-2,-3,-5,8)

# Multiplication
c(2,3,5,7) * c(-2,-3,-5,8)

# Division
c(2,3,5,7) / c(-2,-3,-5,8)

[1]  0  0  0 15

[1]  4  6 10 -1

[1]  -4  -9 -25  56

[1] -1.000 -1.000 -1.000  0.875

In [ ]:
############################################################
# 2. Power Operations
############################################################

# Scalar power
2^3
2**3

# Square root using power
2^0.5
2**0.5

# Negative power
2^-0.5

# Vector squared
c(2,3,5,7)^2

# Vector raised to another vector
c(2,3,5,7)^c(2,3)

# Another vector example
c(1,2,3,4,5,6)^c(2,3,4)

# Different length vectors (Warning)
c(2,3,5,7)^c(2,3,4)

[1] 8

[1] 8

[1] 1.414214

[1] 1.414214

[1] 0.7071068

[1]  4  9 25 49

[1]   4  27  25 343

[1]    1    8   81   16  125 1296

Warning message in c(2, 3, 5, 7)^c(2, 3, 4):
“longer object length is not a multiple of shorter object length”

[1]   4  27 625  49

In [ ]:
############################################################
# 3. Integer Division
############################################################

2 %/% 2
5 %/% 2
7 %/% 3

# Vector with scalar
c(2,3,5,7) %/% 2

# Vector with vector
c(2,3,5,7) %/% c(2,3)

# Warning example
c(2,3,5) %/% c(2,3)

[1] 1

[1] 2

[1] 2

[1] 1 1 2 3

[1] 1 1 2 2

Warning message in c(2, 3, 5)%/%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 1 1 2

In [ ]:
############################################################
# 4. Modulo Division
############################################################

2 %% 2
3 %% 2
7 %% 3
7 %% 4

# Vector with scalar
c(2,3,5,7) %% 2

# Vector with vector
c(2,3,5,7) %% c(2,3)

# Warning example
c(2,3,5) %% c(2,3)

[1] 0

[1] 1

[1] 1

[1] 3

[1] 0 1 1 1

[1] 0 0 1 1

Warning message in c(2, 3, 5)%%c(2, 3):
“longer object length is not a multiple of shorter object length”

[1] 0 0 1

In [ ]:
############################################################
# 5. Built-in Functions
############################################################

# Maximum
max(1.2,3.4,-7.8)
max(c(1.2,3.4,-7.8))

# Minimum
min(1.2,3.4,-7.8)
min(c(1.2,3.4,-7.8))

# Mean
mean(c(2,3,4))

[1] 3.4

[1] 3.4

[1] -7.8

[1] -7.8

[1] 3

In [ ]:
############################################################
# 6. Mathematical Functions
############################################################

# Absolute value
abs(-4)
abs(c(-1,-2,-3,4,5))

# Square root
sqrt(4)
sqrt(c(4,9,16,25))

# Sum
sum(c(2,3,5,7))

# Product
prod(c(2,3,5,7))

# Round
round(1.23)
round(1.83)

# Natural logarithm
log(10)
log(exp(1))
log(c(10,100,1000))

# Base-10 logarithm
log10(10)
log10(100)
log10(c(10,100,1000))

[1] 4

[1] 1 2 3 4 5

[1] 2

[1] 2 3 4 5

[1] 17

[1] 210

[1] 1

[1] 2

[1] 2.302585

[1] 1

[1] 2.302585 4.605170 6.907755

[1] 1

[1] 2

[1] 1 2 3

In [ ]:
############################################################
# 7. Variable Assignment
############################################################

x1 <- c(1,2,3,4)
x1

x2 <- x1^2
x2

[1] 1 2 3 4

[1]  1  4  9 16

In [ ]:
############################################################
# 8. Combining Operations
############################################################

c(1,2,3,4) + sum(c(1,2,3,4))*prod(c(1,2))

abs(c(1,2,3,4) - sum(c(1,2,3,4))*prod(c(1,2)))

[1] 21 22 23 24

[1] 19 18 17 16

In [ ]:
############################################################
# 9. Matrix Creation
############################################################

# Matrix filled column-wise (default)
x <- matrix(
  data=c(1,2,3,4,5,6,7,8),
  nrow=4,
  ncol=2
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
############################################################
# 10. Access Matrix Element
############################################################

x[3,2]

[1] 7

In [ ]:
############################################################
# 11. Matrix by Column
############################################################

x <- matrix(
  data=c(1,2,3,4,5,6,7,8),
  nrow=4,
  ncol=2,
  byrow=FALSE
)

x

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

In [ ]:
############################################################
# 12. Matrix by Row
############################################################

y <- matrix(
  data=c(1,2,3,4,5,6,7,8),
  nrow=4,
  ncol=2,
  byrow=TRUE
)

y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
############################################################
# 13. Matrix Properties
############################################################

# Dimensions
dim(x)

# Number of rows
nrow(x)

# Number of columns
ncol(x)

# Storage mode
mode(x)

# Matrix attributes
attributes(x)

[1] 4 2

[1] 4

[1] 2

[1] "numeric"

$dim
[1] 4 2

In [ ]:
############################################################
# 14. Help
############################################################

help("matrix")